#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FOAMsearch.Resource", IsApplication=true)]

namespace FOAMsearch
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::FOAMsearch.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int filters = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int langs = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int addFilters = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int clearFilters = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int defaultSpinner = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int editFilters = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int filter = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int langSpinner = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int language = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int myListView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int options = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int searchButton = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int spinner = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int spinner2 = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int textDefault = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int tweets = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int txtContent = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int txtLink = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int txtName = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int txtPicture = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int view1 = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListView_Row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Options = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
